server:
  port: 8080
  servlet:
    context-path: /


spring:
  application:
    name: employee_evaluation_system
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/evaluation_system
    username: root
    password: dong_nv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  web:
    resources:
      static-locations: classpath:/static/, file:////C:/Users/HELLO/Documents/Assignment/Day-2/employeeEvaluationSystem/upload_images
#      static-locations: classpath:/static/, file:////C:/Users/dongnv/Documents/Assignment/Day-2/employee_evaluation_system/upload_images
