server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: employee_evaluation_system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/evaluation_system
    username: root
    password: dong_nv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
